version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - hold:
          type: approval
      - test:
          requires:
            - hold
